[build-system]
requires = [
    "scikit-build-core>=0.8",
    "cmake>=3.18",
    "ninja",
    "pybind11[global]>=2.10"
]
build-backend = "scikit_build_core.build"
backend-path = ["."]

[project]
name = "bitmap2svg-cu"
version = "0.2.3"
description = "A library to convert bitmaps to SVG, using C++, OpenCV, with CUDA/FAISS GPU acceleration."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Xiaonan (Nice) Wang", email = "wangxiaonannice@gmail.com" }
]
classifiers = [ # Recommended for PyPI
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License", # Example, change if different
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: C++",
    "Operating System :: POSIX :: Linux", # Likely, given CUDA/FAISS focus
    "Topic :: Multimedia :: Graphics :: Converters",
    "Topic :: Scientific/Engineering :: Image Processing"
]
keywords = ["svg", "bitmap", "vectorization", "gpu", "cuda", "faiss", "opencv"]

dependencies = [
    "numpy",
    "opencv-python",
    "Pillow" 
]

[project.urls]
Homepage = "https://github.com/Opensource-Nice-Arishi/kaggle_drawing_with_LLMs/tree/bitmap2svg-cu-v0.2.3"

[tool.scikit-build]
cmake.source-dir = "."
cmake.targets = ["bitmap2svg_core"]

# Optional: if need to specify metadata for a specific package
[tool.scikit-build.metadata.وں<x_bin_108>bitmap2svg-cu"] 