[build-system]
requires = ["scikit-build-core", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "bitmap2svg"
version = "0.2.0"
description = "Convert bitmap images to SVG using Potrace and C++"
authors = [{ name = "Xiaonan (Nice) Wang", email = "wangxiaonannice@gmail.com" }]
license = "MIT"
readme = "README.md"
dependencies = ["numpy"]

[tool.scikit-build]
cmake.source-dir = "."
cmake.version = "3.15"
build.verbose = true
