[build-system]
requires = [
    "setuptools>=61.0",    # Recommended modern setuptools
    "wheel",               # For building wheels
    "pybind11>=2.6.0"      # For building the C++ extension
]
build-backend = "setuptools.build_meta"
backend-path = ["."]

[project]
name = "bitmap2svg"
version = "0.2.0"
description = "A Python wrapper for C++ bitmap to SVG conversion using Potrace."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT License" } # Or use: file = "LICENSE.txt"
authors = [
    { name = "Xiaonan (Nice) Wang", email = "wangxiaonannice@gmail.com" }
]
keywords = ["svg", "bitmap", "image conversion", "vector graphics", "potrace", "c++"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Topic :: Multimedia :: Graphics :: Converters",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "numpy>=1.16"
]

[project.urls]
Homepage = "https://github.com/Opensource-Nice-Arishi/kaggle_drawing_with_LLMs/tree/bitmap2svg"
Repository = "https://github.com/Opensource-Nice-Arishi/kaggle_drawing_with_LLMs/tree/bitmap2svg"
