name: Build Bitmap2SVG Python package

on:
  push:
    branches: [bitmap2svg]
  pull_request:
    branches: [bitmap2svg]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install system dependencies (for potrace)
      run: |
        sudo apt-get update
        sudo apt-get install -y libpotrace-dev pkg-config

    # - name: Check /usr/local/lib/pkgconfig/ for .pc files
    #   run: ls /usr/local/lib/pkgconfig/*.pc

    - name: Search for files containing "potrace"
      run: sudo find / -name "*potrace*" -print

    - name: Reinstall libpotrace-dev and check output
      run: |
        sudo apt-get remove --purge -y libpotrace-dev
        sudo apt-get update
        sudo apt-get install -y libpotrace-dev

    - name: Check pkg-config default path
      run: pkg-config --variable pc_path pkg-config

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build scikit-build-core numpy pybind11 cmake ninja

    - name: Build package
      run: |
        python -m build --no-isolation

    - name: Test import
      run: |
        pip install dist/*.whl
        python -c "import bitmap2svg; print(bitmap2svg.convert_image_to_svg.__doc__)"
