name: Build and Package

on:
  push:
    branches: [ bitmap2svg ]
  pull_request:
    branches: [ bitmap2svg ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Potrace dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpotrace-dev

      - name: Set CMAKE_PREFIX_PATH
        run: echo "CMAKE_PREFIX_PATH=/usr:/usr/local:/opt/local" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build -j ${{ github.event_name == 'push' && '2' || '4' }}

      - name: Test
        run: cmake --build build --target test 
