name: Build Bitmap2SVG

on:
  push:
    branches: [bitmap2svg]
  pull_request:
    branches: [bitmap2svg]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpotrace-dev cmake
          pip install -U pip
          pip install build numpy

      - name: Build package
        run: |
          python -m build

      - name: Test import
        run: |
          pip install dist/*.whl
          python -c "import bitmap2svg; print(bitmap2svg.convert_image_to_svg.__doc__)"
